name: Run integration test
description: Prepares the environment and runs an integration test using Cypress

inputs:
  integration:
    description: The integration test to run
    required: true
  node:
    description: The Node version to use
    required: false
    default: 18
  dotenv:
    description: The path to the .env file
    required: false
    default: .env.sample

runs:
  using: composite

  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Prepare dependencies
      shell: bash
      run: |
        pnpm import

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'

    - name: Update /etc/hosts
      shell: bash
      run: |
        sudo echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts

    - name: Move dotenv file
      shell: bash
      run: |
        mv examples/${{ inputs.integration }}/${{ inputs.dotenv }} examples/${{ inputs.integration }}/.env

    - name: Install dependencies
      shell: bash
      run: |
        pnpm i

    - name: Start mock API server
      shell: bash
      run: |
        cd examples/users-api
        pnpm i
        pnpm run start &
      env:
        DOMAIN: your-tenant.auth0.com
        AUDIENCE: https://api.example.com/users
        PORT: 3001

    - name: Start application
      shell: bash
      run: |
        cd examples/${{ inputs.integration }}
        pnpm i
        pnpm run start &
      env:
        PORT: 3000

    - name: Run Cypress test
      uses: cypress-io/github-action@v6
      with:
        spec: cypress/integration/smoke.test.ts
        install: false
        wait-on: 'http://localhost:3001/, http://localhost:3000'
