name: RL-Secure Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      RL_SECURE_LICENSE:
        required: true
      RL_SECURE_SITE_KEY:
        required: true
      SIGNAL_HANDLER_TOKEN:
        required: true
      PROD_TOOLS_USER:
        required: true
      PROD_TOOLS_TOKEN:
        required: true

jobs:
  rl-scanner:
    name: Run Reversing Labs Scanner
    runs-on: ubuntu-latest
    outputs:
      scan-status: ${{ steps.rl-scan-conclusion.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build package
        uses: ./.github/actions/build
        with:
          node: ${{ inputs.node-version }}

      - name: Create tgz build artifact
        run: |
          tar -czvf ${{ inputs.artifact-name }} *

      - id: get_version
        uses: ./.github/actions/get-version

      - name: Run RL Scanner
        id: rl-scan-conclusion
        uses: ./.github/actions/rl-scanner
        with:
          artifact-path: "$(pwd)/${{ inputs.artifact-name }}"
          version: "${{ steps.get_version.outputs.version }}"
          repository: "${{ github.repository }}"
          commit: "${{ github.sha }}"
        env:
          RL_SECURE_LICENSE: ${{ secrets.RL_SECURE_LICENSE }}
          RL_SECURE_SITE_KEY: ${{ secrets.RL_SECURE_SITE_KEY }}
          SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
          PROD_TOOLS_USER: ${{ secrets.PROD_TOOLS_USER }}
          PROD_TOOLS_TOKEN: ${{ secrets.PROD_TOOLS_TOKEN }}

      - name: Output scan result
        run: echo "scan-status=${{ steps.rl-scan-conclusion.outcome }}" >> $GITHUB_ENV
